services:
  postgres:
    image: 'postgres:latest'
    container_name: library_db
    environment:
      - 'POSTGRES_DB=library'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    ports:
      - "5432:5432"
